# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdatePasswordDialog(object):
    def setupUi(self, UpdatePasswordDialog):
        UpdatePasswordDialog.setObjectName("UpdatePasswordDialog")
        UpdatePasswordDialog.resize(393, 228)
        self.centralwidget = QtWidgets.QWidget(UpdatePasswordDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 61, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 140, 111, 28))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 60, 131, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 90, 131, 22))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        UpdatePasswordDialog.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UpdatePasswordDialog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 393, 26))
        self.menubar.setObjectName("menubar")
        UpdatePasswordDialog.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UpdatePasswordDialog)
        self.statusbar.setObjectName("statusbar")
        UpdatePasswordDialog.setStatusBar(self.statusbar)

        self.retranslateUi(UpdatePasswordDialog)
        QtCore.QMetaObject.connectSlotsByName(UpdatePasswordDialog)

    def retranslateUi(self, UpdatePasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        UpdatePasswordDialog.setWindowTitle(_translate("UpdatePasswordDialog", "MainWindow"))
        self.label.setText(_translate("UpdatePasswordDialog", "Kullanıcı Adı:"))
        self.label_2.setText(_translate("UpdatePasswordDialog", "Yeni Şifre:"))
        self.pushButton.setText(_translate("UpdatePasswordDialog", "Şifreyi Güncelle"))
